<a href="https://colab.research.google.com/github/MyoRasp/TIA/blob/main/TIA_Actividad_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pathlib

import pandas as pd #import read_csv
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

import tensorflow as tf
from tensorflow import keras

%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

In [10]:
#CÃ³digo para cargar el Dataset

url = r"https://raw.githubusercontent.com/MyoRasp/Dataset/main/Data/ICU/Data-on-hospital-and-ICU-admission-rates-and-current-occupancy-for-COVID-19.csv" 

df = pd.read_csv(url)

In [11]:
df.head()

   country                 indicator year_week  value
0  Austria  Daily hospital occupancy  2020-W14  856.0
1  Austria  Daily hospital occupancy  2020-W14  823.0
2  Austria  Daily hospital occupancy  2020-W14  829.0
3  Austria  Daily hospital occupancy  2020-W14  826.0
4  Austria  Daily hospital occupancy  2020-W14  712.0